name: Auto-pip

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  auto-pip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build twine

      - name: Update version
        run: |
          # Extract version from git tag
          # get the latest tag
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          # Update versions in files
          sed -i "s/version=\".*\"/version=\"${LATEST_TAG}\"/" setup.py

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*